import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { makeSprite, hexToColor } from '../src/core.js';
import { createDemo } from '../src/demo.js';
import { buildTileset } from '../src/tiles.js';
import { makeTilemap, renderTilemap } from '../src/tilemap.js';
import { serializeWorkspace, parseWorkspace } from '../src/storage.js';
const w=createDemo(),sheet=makeSprite('Pattern sheet',32,32),colors=['#ff0000','#00ff00','#0000ff','#ffff00'].map(hexToColor);
for(let y=0;y<32;y++)for(let x=0;x<32;x++)sheet.layers[0].pixels[y*32+x]=colors[Math.floor(y/16)*2+Math.floor(x/16)];
w.sprites.push(sheet);
const terrain=(id,a,b,mode='wang')=>({...buildTileset(a,b,{size:16,columns:8,mode,terrainA:a.id,terrainB:b.id}),id,kind:'tileset',name:id});
w.tilesets=[terrain('Grass-water',w.sprites[1],w.sprites[2]),terrain('Stone-water',w.sprites[3],w.sprites[2]),terrain('Blob-grass',w.sprites[1],w.sprites[2],'blob')];
w.tilesets[1].animations={0:{frames:[0,1],fps:4}};w.tilemaps=[makeTilemap('Pattern world',6,6,w.tilesets[0])];
const browser=await chromium.launch({...(process.env.PIXFIT_BROWSER?{executablePath:process.env.PIXFIT_BROWSER}:{channel:'chrome'}),headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
const click=action=>page.locator(`[data-action="${action}"]`).first().click();
const submit=()=>page.click('#dialog button[type="submit"]');
const paint=async(x,y,button='left')=>{const box=await page.locator('#art-canvas').boundingBox();await page.mouse.click(box.x+(x+.5)*box.width/6,box.y+(y+.5)*box.height/6,{button});};
const saved=async()=>{
  await page.waitForFunction(()=>document.querySelector('#save-status')?.textContent.includes('All changes saved'));
  return parseWorkspace(await page.evaluate(()=>new Promise(resolve=>{const r=indexedDB.open('pixfit-studio',1);r.onsuccess=()=>{const db=r.result,g=db.transaction('workspace').objectStore('workspace').get('current');g.onsuccess=()=>{resolve(g.result);db.close();};};})));
};
try{
  await page.addInitScript(data=>{if(!sessionStorage.getItem('fixture')){localStorage.setItem('pixfit-workspace',JSON.stringify(data));sessionStorage.setItem('fixture','1');}},serializeWorkspace(w));
  await page.goto('http://127.0.0.1:5173');await click('new-collection');await page.fill('[name="name"]','World collection');
  for(const t of w.tilesets)await page.check(`[name="terrain"][value="${t.id}"]`);await submit();
  assert.equal((await saved()).collections[0].terrainIds.length,3);
  await click('edit-collection');assert.equal(await page.locator('[name="terrain"]:checked').count(),3);await page.keyboard.press('Escape');
  const downloading=page.waitForEvent('download');await click('export-collection');const zip=await readFile(await (await downloading).path());
  const root='.screenshots/godot-collection';await mkdir(root,{recursive:true});
  const files=new Map();for(let offset=0;zip.readUInt32LE(offset)===0x04034b50;){const size=zip.readUInt32LE(offset+18),length=zip.readUInt16LE(offset+26),extra=zip.readUInt16LE(offset+28),start=offset+30+length+extra,name=zip.subarray(offset+30,offset+30+length).toString(),bytes=zip.subarray(start,start+size);files.set(name,bytes);await mkdir(`${root}/${name.slice(0,name.lastIndexOf('/'))}`,{recursive:true});await writeFile(`${root}/${name}`,bytes);offset=start+size;}
  const tres=files.get('pixfit-world-collection/tileset.tres').toString();assert.match(tres,/terrain_set_1\/mode = 0/);assert.match(tres,/sources\/3 =/);
  await page.locator('.library-open').filter({hasText:'Pattern world'}).click();
  await page.selectOption('#map-collection',(await saved()).collections[0].id);assert.equal(await page.locator('#map-tileset option').count(),4);
  await page.click('[data-action="map-tile"][data-index="3"]');await paint(4,4);
  await page.selectOption('#map-tileset','Stone-water');await paint(5,5);
  await page.selectOption('#map-tileset','textures');await page.selectOption('#map-texture',sheet.id);assert.equal(await page.locator('[data-texture-tile]').count(),4);
  await page.click('[data-action="texture-tile"][data-index="3"]');await paint(0,0);await paint(3,0);
  let m=(await saved()).tilemaps[0];assert.equal(m.layers[0].cells[0],4);assert.equal(m.layers[0].cells[3],4);assert.equal(m.layers[0].terrain[0],7);assert.equal(m.layers[0].decals.length,0);
  await click('undo');assert.equal((await saved()).tilemaps[0].layers[0].cells[3],0);await click('redo');
  await page.click('[data-action="texture-tile"][data-index="0"]');await page.click('[data-action="texture-tile"][data-index="3"]',{modifiers:['Shift']});assert.equal(await page.locator('[data-action="texture-tile"][aria-pressed="true"]').count(),4);
  await click('save-map-pattern');await page.fill('[name="name"]','Four colors');await submit();await paint(1,1);
  m=(await saved()).tilemaps[0];assert.equal(m.patterns[0].name,'Four colors');assert.deepEqual([7,8,13,14].map(i=>m.layers[0].cells[i]),[1,2,3,4]);
  await page.click('[data-action="map-tool"][data-tool="rect"]');const box=await page.locator('#art-canvas').boundingBox();await page.mouse.move(box.x+box.width/12,box.y+box.height*7/12);await page.mouse.down();await page.mouse.move(box.x+box.width*5/12,box.y+box.height*9/12,{steps:3});await page.mouse.up();
  m=(await saved()).tilemaps[0];assert.deepEqual([18,19,20,24,25,26].map(i=>m.layers[0].cells[i]),[1,2,1,3,4,3]);
  await page.click('[data-action="map-tool"][data-tool="picker"]');await paint(2,2);assert.equal(await page.locator('[data-action="texture-tile"][data-index="3"]').getAttribute('aria-pressed'),'true');
  await page.reload();await page.locator('.library-open').filter({hasText:'Pattern world'}).click();assert.deepEqual((await saved()).tilemaps[0].layers,m.layers);assert.deepEqual((await saved()).tilemaps[0].patterns,m.patterns);
  await page.selectOption('#map-tileset','textures');assert.equal(await page.locator('[data-map-brush]').count(),2);
  await click('export');const pngDownload=page.waitForEvent('download');await submit();const png=await readFile(await (await pngDownload).path());assert.equal(png.readUInt32BE(16),96);assert.equal(png.readUInt32BE(20),96);await page.keyboard.press('Escape');
  await page.screenshot({path:'.screenshots/pattern-map.png',fullPage:true});await page.setViewportSize({width:700,height:900});await page.screenshot({path:'.screenshots/pattern-map-narrow.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});await click('settings');
  const backing=page.waitForEvent('download');await page.click('#dialog [data-action="backup"]');const backup=await backing;await backup.saveAs('.screenshots/pattern-backup.json');await page.keyboard.press('Escape');
  await page.setInputFiles('#json-file','.screenshots/pattern-backup.json');await page.selectOption('[name="mode"]','merge');await submit();await page.locator('#dialog').waitFor({state:'hidden'});
  const merged=await saved();assert.equal(merged.collections.length,2);assert.equal(merged.tilemaps.length,2);assert.notEqual(merged.tilemaps[0].patterns[0].id,merged.tilemaps[1].patterns[0].id);assert.deepEqual(renderTilemap(merged.tilemaps[0],merged,0),renderTilemap(merged.tilemaps[1],merged,0));
  await click('new-document');await page.click('#dialog [data-action="new-map"]');await page.fill('[name="name"]','Custom grid');await page.fill('[name="width"]','8');await page.fill('[name="height"]','8');await page.fill('[name="cell-width"]','8');await page.fill('[name="cell-height"]','8');await submit();
  await page.selectOption('#map-tileset','textures');await page.selectOption('#map-texture',sheet.id);assert.equal(await page.locator('[data-texture-tile]').count(),16);assert.equal((await saved()).tilemaps.at(-1).cellWidth,8);
  assert.deepEqual(errors,[]);console.log('Browser checks passed: collections, combined Godot download, mixed terrains, texture grid, patterns, rectangle repeat, picker, undo/redo, persistence, and one-image PNG.');
}finally{await browser.close();}
